// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShooterSpeed.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ShooterSpeed::ShooterSpeed(double speed, bool charge): Command() {
    m_speed = speed;
    m_charge = charge;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ShooterSpeed::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ShooterSpeed::Execute() {
	Robot::shooter->SetShooterSpeed(m_speed);
	if(m_charge) {
		if(TimeSinceInitialized() > 2.0) {
			SmartDashboard::PutBoolean("Shooter Ready", true);
		}else{
	        SmartDashboard::PutBoolean("Shooter Ready", false);
		}
	}
}

// Make this return true when this Command no longer needs to run execute()
bool ShooterSpeed::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ShooterSpeed::End() {
	Robot::shooter->SetShooterSpeed(0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterSpeed::Interrupted() {
	End();
}
