// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Robot.h"

//access pointer objects delcared in Robot.h
std::shared_ptr<Drivetrain> Robot::drivetrain;
std::shared_ptr<ShooterTShirt> Robot::shootertshirt;
std::shared_ptr<ShooterFrisbee> Robot::shooterfrisbee;
std::unique_ptr<OI> Robot::oi;


void Robot::RobotInit() {
	RobotMap::init();
	//start subsystems
    drivetrain.reset(new Drivetrain());
    shootertshirt.reset(new ShooterTShirt());
    shooterfrisbee.reset(new ShooterFrisbee());
    //starts operator interface
	oi.reset(new OI());

	//instantiate the command used for the autonomous period
  }

void Robot::DisabledInit(){

}

void Robot::DisabledPeriodic() {
	frc::Scheduler::GetInstance()->Run();
	//the joystick throttle

	//puts if we are using the chooser or not on the smartdashboard
	frc::SmartDashboard::PutBoolean("Using Chooser", useChooser);
}

void Robot::AutonomousInit() {	//start autonomous
	Robot::drivetrain->SetAutonomous(true);

	if (autonomousCommand.get() != nullptr)
		autonomousCommand->Start();
	//resets drivetrain encoders to zero
	Robot::drivetrain->ResetEncoders();
}

void Robot::AutonomousPeriodic() {
	frc::Scheduler::GetInstance()->Run();
}

void Robot::TeleopInit() {
	//stops autonomous command
	if (autonomousCommand.get() != nullptr)
		autonomousCommand->Cancel();
	Robot::drivetrain->SetAutonomous(false);
}

void Robot::TeleopPeriodic() {
	frc::Scheduler::GetInstance()->Run();
	//print information to smartdashboard
	frc::SmartDashboard::PutNumber("left encoder", RobotMap::drivetrainLeftEncoder->GetDistance());
	frc::SmartDashboard::PutNumber("right encoder", RobotMap::drivetrainRightEncoder->GetDistance());
	frc::SmartDashboard::PutBoolean("nos status" , Robot::oi->DriveNosKick());
}

void Robot::TestPeriodic() {
	lw->Run();
}

START_ROBOT_CLASS(Robot);

